services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gym-classification-api
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - .git
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
      - ./data:/data
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - CORS_ORIGINS=http://localhost:3000
